// Generated by scripts/gen-types.mjs (npm run gen:types). Do not edit by hand.
// Domain types inferred from the Zod schemas in src/schemas, so the two can never drift.
// Names follow the BLUEPRINT.md data model.
import type { z } from "zod";
import type * as s from "@/schemas";

// common
export type Id = z.infer<typeof s.Id>;
export type IsoDateTime = z.infer<typeof s.IsoDateTime>;
export type IsoDate = z.infer<typeof s.IsoDate>;
export type Currency = z.infer<typeof s.Currency>;
export type Money = z.infer<typeof s.Money>;
export type MoneyRange = z.infer<typeof s.MoneyRange>;
export type RelatedType = z.infer<typeof s.RelatedType>;
export type ApprovalStatus = z.infer<typeof s.ApprovalStatus>;
export type Confidence = z.infer<typeof s.Confidence>;

// account
export type AccountKind = z.infer<typeof s.AccountKind>;
export type Sector = z.infer<typeof s.Sector>;
export type PaymentTerms = z.infer<typeof s.PaymentTerms>;
export type RelationshipHealth = z.infer<typeof s.RelationshipHealth>;
export type PendingChange = z.infer<typeof s.PendingChange>;
export type Account = z.infer<typeof s.Account>;
export type ContactRole = z.infer<typeof s.ContactRole>;
export type Contact = z.infer<typeof s.Contact>;
export type Country = z.infer<typeof s.Country>;
export type Address = z.infer<typeof s.Address>;
export type BrewfittTeamRole = z.infer<typeof s.BrewfittTeamRole>;
export type BrewfittTeamMember = z.infer<typeof s.BrewfittTeamMember>;
export type AccountPatch = z.infer<typeof s.AccountPatch>;
export type AddressInput = z.infer<typeof s.AddressInput>;
export type ContactInput = z.infer<typeof s.ContactInput>;

// catalogue
export type CatalogueSection = z.infer<typeof s.CatalogueSection>;
export type Category = z.infer<typeof s.Category>;
export type Unit = z.infer<typeof s.Unit>;
export type Product = z.infer<typeof s.Product>;
export type PriceList = z.infer<typeof s.PriceList>;
export type PriceListLine = z.infer<typeof s.PriceListLine>;
export type StockStatus = z.infer<typeof s.StockStatus>;
export type StockPosition = z.infer<typeof s.StockPosition>;
export type StockForecastMonth = z.infer<typeof s.StockForecastMonth>;
export type StockForecast = z.infer<typeof s.StockForecast>;
export type OnTimeDelivery = z.infer<typeof s.OnTimeDelivery>;
export type CustomerStats = z.infer<typeof s.CustomerStats>;
export type SupplierPerformance = z.infer<typeof s.SupplierPerformance>;
export type ProductListQuery = z.infer<typeof s.ProductListQuery>;
export type PriceListResponse = z.infer<typeof s.PriceListResponse>;
export type PriceListExport = z.infer<typeof s.PriceListExport>;

// configurator
export type ConfiguratorStepId = z.infer<typeof s.ConfiguratorStepId>;
export type VenueType = z.infer<typeof s.VenueType>;
export type Beverage = z.infer<typeof s.Beverage>;
export type ConfiguratorStep = z.infer<typeof s.ConfiguratorStep>;
export type ConfiguratorGroup = z.infer<typeof s.ConfiguratorGroup>;
export type QuantityBasis = z.infer<typeof s.QuantityBasis>;
export type OptionLine = z.infer<typeof s.OptionLine>;
export type OptionCompatibility = z.infer<typeof s.OptionCompatibility>;
export type ConfiguratorOption = z.infer<typeof s.ConfiguratorOption>;
export type ConfiguratorRules = z.infer<typeof s.ConfiguratorRules>;
export type DispensePoint = z.infer<typeof s.DispensePoint>;
export type ConfigurationSelections = z.infer<typeof s.ConfigurationSelections>;
export type ConfigurationLine = z.infer<typeof s.ConfigurationLine>;
export type Configuration = z.infer<typeof s.Configuration>;
export type ConfigurationInput = z.infer<typeof s.ConfigurationInput>;
export type ConfigurationPatch = z.infer<typeof s.ConfigurationPatch>;

// trade
export type BasketLine = z.infer<typeof s.BasketLine>;
export type Basket = z.infer<typeof s.Basket>;
export type BasketPatch = z.infer<typeof s.BasketPatch>;
export type MockCardPayment = z.infer<typeof s.MockCardPayment>;
export type BasketQuoteRequest = z.infer<typeof s.BasketQuoteRequest>;
export type CheckoutRequest = z.infer<typeof s.CheckoutRequest>;
export type QuoteStatus = z.infer<typeof s.QuoteStatus>;
export type QuoteLine = z.infer<typeof s.QuoteLine>;
export type Quote = z.infer<typeof s.Quote>;
export type DeclineQuoteRequest = z.infer<typeof s.DeclineQuoteRequest>;
export type RfqStatus = z.infer<typeof s.RfqStatus>;
export type RfqLine = z.infer<typeof s.RfqLine>;
export type Rfq = z.infer<typeof s.Rfq>;
export type SupplierQuoteLine = z.infer<typeof s.SupplierQuoteLine>;
export type SupplierQuote = z.infer<typeof s.SupplierQuote>;
export type RfqResponseRequest = z.infer<typeof s.RfqResponseRequest>;
export type SalesOrderStatus = z.infer<typeof s.SalesOrderStatus>;
export type SalesOrderLine = z.infer<typeof s.SalesOrderLine>;
export type SalesOrder = z.infer<typeof s.SalesOrder>;
export type PurchaseOrderStatus = z.infer<typeof s.PurchaseOrderStatus>;
export type PurchaseOrderLine = z.infer<typeof s.PurchaseOrderLine>;
export type PurchaseOrder = z.infer<typeof s.PurchaseOrder>;
export type OrderType = z.infer<typeof s.OrderType>;
export type DeliveryStatus = z.infer<typeof s.DeliveryStatus>;
export type DeliveryLine = z.infer<typeof s.DeliveryLine>;
export type Delivery = z.infer<typeof s.Delivery>;
export type ChangeRequest = z.infer<typeof s.ChangeRequest>;
export type ChangeRequestInput = z.infer<typeof s.ChangeRequestInput>;
export type SalesOrderDetail = z.infer<typeof s.SalesOrderDetail>;
export type PurchaseOrderDetail = z.infer<typeof s.PurchaseOrderDetail>;
export type RfqWithResponse = z.infer<typeof s.RfqWithResponse>;

// finance
export type InvoiceKind = z.infer<typeof s.InvoiceKind>;
export type InvoiceStatus = z.infer<typeof s.InvoiceStatus>;
export type AgeingBand = z.infer<typeof s.AgeingBand>;
export type Invoice = z.infer<typeof s.Invoice>;
export type PaymentMethod = z.infer<typeof s.PaymentMethod>;
export type PaymentAllocation = z.infer<typeof s.PaymentAllocation>;
export type Payment = z.infer<typeof s.Payment>;
export type PaymentRun = z.infer<typeof s.PaymentRun>;
export type StatementLine = z.infer<typeof s.StatementLine>;
export type Statement = z.infer<typeof s.Statement>;
export type PayInvoiceRequest = z.infer<typeof s.PayInvoiceRequest>;

// service
export type JobStatus = z.infer<typeof s.JobStatus>;
export type Job = z.infer<typeof s.Job>;
export type CustomerCaseKind = z.infer<typeof s.CustomerCaseKind>;
export type SupplierCaseKind = z.infer<typeof s.SupplierCaseKind>;
export type CaseKind = z.infer<typeof s.CaseKind>;
export type CaseUrgency = z.infer<typeof s.CaseUrgency>;
export type CaseStatus = z.infer<typeof s.CaseStatus>;
export type EngineerNote = z.infer<typeof s.EngineerNote>;
export type Case = z.infer<typeof s.Case>;
export type CaseInput = z.infer<typeof s.CaseInput>;
export type CasePatch = z.infer<typeof s.CasePatch>;

// content
export type KnowledgeType = z.infer<typeof s.KnowledgeType>;
export type SubmissionStatus = z.infer<typeof s.SubmissionStatus>;
export type KnowledgeItem = z.infer<typeof s.KnowledgeItem>;
export type KnowledgeSubmissionInput = z.infer<typeof s.KnowledgeSubmissionInput>;
export type DocumentCategory = z.infer<typeof s.DocumentCategory>;
export type FileType = z.infer<typeof s.FileType>;
export type Document = z.infer<typeof s.Document>;
export type DocumentUploadInput = z.infer<typeof s.DocumentUploadInput>;
export type SupplierProduct = z.infer<typeof s.SupplierProduct>;
export type SupplierProductInput = z.infer<typeof s.SupplierProductInput>;
export type SupplierProductPatch = z.infer<typeof s.SupplierProductPatch>;
export type OfferStatus = z.infer<typeof s.OfferStatus>;
export type Offer = z.infer<typeof s.Offer>;
export type OfferInput = z.infer<typeof s.OfferInput>;

// comms
export type Side = z.infer<typeof s.Side>;
export type Channel = z.infer<typeof s.Channel>;
export type Participant = z.infer<typeof s.Participant>;
export type Thread = z.infer<typeof s.Thread>;
export type Message = z.infer<typeof s.Message>;
export type ThreadSummary = z.infer<typeof s.ThreadSummary>;
export type ThreadDetail = z.infer<typeof s.ThreadDetail>;
export type NewMessageInput = z.infer<typeof s.NewMessageInput>;
export type NewThreadInput = z.infer<typeof s.NewThreadInput>;
export type NotificationKind = z.infer<typeof s.NotificationKind>;
export type Notification = z.infer<typeof s.Notification>;
export type NotificationPatch = z.infer<typeof s.NotificationPatch>;

// ai
export type InsightCategory = z.infer<typeof s.InsightCategory>;
export type InsightSeverity = z.infer<typeof s.InsightSeverity>;
export type AIInsight = z.infer<typeof s.AIInsight>;
export type AskRequest = z.infer<typeof s.AskRequest>;
export type AskSource = z.infer<typeof s.AskSource>;
export type AskResponse = z.infer<typeof s.AskResponse>;

// session
export type PersonaKind = z.infer<typeof s.PersonaKind>;
export type Persona = z.infer<typeof s.Persona>;
export type CreditPosition = z.infer<typeof s.CreditPosition>;
export type Me = z.infer<typeof s.Me>;
export type PersonaOption = z.infer<typeof s.PersonaOption>;
