// Regenerates src/types/index.ts from the schema files. Run after adding or renaming a schema.
import { readFileSync, writeFileSync } from "node:fs";

const files = [
  "common",
  "account",
  "catalogue",
  "configurator",
  "trade",
  "finance",
  "service",
  "content",
  "comms",
  "ai",
  "session",
];

let out = `// Generated by scripts/gen-types.mjs (npm run gen:types). Do not edit by hand.
// Domain types inferred from the Zod schemas in src/schemas, so the two can never drift.
// Names follow the BLUEPRINT.md data model.
import type { z } from "zod";
import type * as s from "@/schemas";
`;

for (const f of files) {
  const src = readFileSync(`src/schemas/${f}.ts`, "utf8");
  const names = [...src.matchAll(/^export const (\w+) =/gm)].map((m) => m[1]);
  out +=
    `\n// ${f}\n` +
    names.map((n) => `export type ${n} = z.infer<typeof s.${n}>;`).join("\n") +
    "\n";
}

writeFileSync("src/types/index.ts", out);
console.log("src/types/index.ts regenerated");
